# Generated by Django 2.2.5 on 2019-09-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hackernews',
            fields=[
                ('story_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('title', models.TextField()),
                ('sentiment', models.CharField(max_length=20)),
                ('url', models.TextField(max_length=100)),
                ('upvotes', models.IntegerField()),
            ],
            options={
                'db_table': 'app_hackernews',
            },
        ),
    ]
